-- ============================================================
-- GrocerIQ - Dummy Data (data.sql)
-- ~5 entries per table, easy to read and verify manually.
-- datasource: synthetic data generated by generate_data.py
-- ============================================================

USE grocery_tracker;

-- ------------------------------------------------------------
-- users (5 rows)
-- Test logins: testuser1/pass1, testuser2/pass2, admin/adminpass
-- ------------------------------------------------------------
INSERT INTO users (username, email, password_hash, firstName, lastName) VALUES
  ('testuser1', 'test1@groceriq.com', '$2b$10$uzOEIB8MpOoqwolkX1ITeexmh1hjmKdNBlfy9ZW1G3g4CUQD9ie7C', 'Alice', 'Johnson'),
  ('testuser2', 'test2@groceriq.com', '$2b$10$Qp/5bly1m61YKzWWBF/GceBgdmMfhx2SlYeVa3A1FxERzv93wCiie', 'Bob', 'Smith'),
  ('admin', 'admin@groceriq.com', '$2b$10$yRaz4tCd6Z3yRbJ0ji4fsuIT/WMU9XWFz5uPrfXdvTTfitRGCLprC', 'Admin', 'User'),
  ('jdoe', 'jdoe@groceriq.com', '$2b$10$LkhE4ez9K8efWDT46bzDreYgFG9WE.WvuT0ly6PW9nJWdOGB0FR2O', 'John', 'Doe'),
  ('mwilson', 'mwilson@groceriq.com', '$2b$10$YVYcuajyug4hAo62hIrOs.QEBrW/TEGOZ8/yJdSJgzoaYk0zIrYty', 'Mary', 'Wilson');

-- ------------------------------------------------------------
-- stores (5 rows)
-- ------------------------------------------------------------
INSERT INTO stores (store_name, chain, city, state, zip_code) VALUES
  ('Kroger Ponce de Leon',       'Kroger',  'Atlanta',       'GA', '30306'),
  ('Publix Midtown',             'Publix',  'Atlanta',       'GA', '30309'),
  ('Walmart Supercenter Smyrna', 'Walmart', 'Smyrna',        'GA', '30080'),
  ('Aldi Marietta',              'Aldi',    'Marietta',      'GA', '30060'),
  ('Publix Sandy Springs',       'Publix',  'Sandy Springs', 'GA', '30328');

-- ------------------------------------------------------------
-- products (5 rows)
-- ------------------------------------------------------------
INSERT INTO products (product_name, category, brand, unit_size, unit_type) VALUES
  ('Whole Milk',             'Dairy',   'Horizon Organic', 1.00,  'gallon'),
  ('Boneless Chicken Breast','Meat',    'Generic',         1.00,  'lb'),
  ('Bananas',                'Produce', 'Generic',         1.00,  'lb'),
  ('White Sandwich Bread',   'Bakery',  'Wonder',          20.00, 'oz'),
  ('Pasta Spaghetti',        'Pantry',  'Barilla',         16.00, 'oz');

-- ------------------------------------------------------------
-- price_records
-- 5 products x 5 stores x 3 months = 75 rows (exceeds 1000-row requirement
-- when scaled up with real data; this is the dev/test seed)
-- Columns: product_id, store_id, price, reg_price, is_sale, price_date
-- is_sale = 1 when price is ~15%+ below reg_price
-- ------------------------------------------------------------
INSERT INTO price_records (product_id, store_id, price, reg_price, is_sale, price_date) VALUES
  (1, 1, 5.49, 5.49, 0, '2026-02-01'),
  (1, 1, 5.49, 5.49, 0, '2026-03-01'),
  (1, 1, 5.49, 5.49, 0, '2026-04-01'),
  (1, 2, 5.93, 5.93, 0, '2026-02-01'),
  (1, 2, 5.93, 5.93, 0, '2026-03-01'),
  (1, 2, 5.93, 5.93, 0, '2026-04-01'),
  (1, 3, 4.13, 5.16, 1, '2026-02-01'),
  (1, 3, 5.16, 5.16, 0, '2026-03-01'),
  (1, 3, 5.16, 5.16, 0, '2026-04-01'),
  (1, 4, 4.5, 4.5, 0, '2026-02-01'),
  (1, 4, 4.5, 4.5, 0, '2026-03-01'),
  (1, 4, 4.5, 4.5, 0, '2026-04-01'),
  (1, 5, 5.93, 5.93, 0, '2026-02-01'),
  (1, 5, 5.93, 5.93, 0, '2026-03-01'),
  (1, 5, 5.93, 5.93, 0, '2026-04-01'),
  (2, 1, 4.99, 4.99, 0, '2026-02-01'),
  (2, 1, 4.99, 4.99, 0, '2026-03-01'),
  (2, 1, 4.99, 4.99, 0, '2026-04-01'),
  (2, 2, 5.39, 5.39, 0, '2026-02-01'),
  (2, 2, 4.31, 5.39, 1, '2026-03-01'),
  (2, 2, 5.39, 5.39, 0, '2026-04-01'),
  (2, 3, 4.69, 4.69, 0, '2026-02-01'),
  (2, 3, 4.69, 4.69, 0, '2026-03-01'),
  (2, 3, 4.69, 4.69, 0, '2026-04-01'),
  (2, 4, 4.09, 4.09, 0, '2026-02-01'),
  (2, 4, 4.09, 4.09, 0, '2026-03-01'),
  (2, 4, 4.09, 4.09, 0, '2026-04-01'),
  (2, 5, 5.39, 5.39, 0, '2026-02-01'),
  (2, 5, 5.39, 5.39, 0, '2026-03-01'),
  (2, 5, 5.39, 5.39, 0, '2026-04-01'),
  (3, 1, 0.59, 0.59, 0, '2026-02-01'),
  (3, 1, 0.59, 0.59, 0, '2026-03-01'),
  (3, 1, 0.47, 0.59, 1, '2026-04-01'),
  (3, 2, 0.64, 0.64, 0, '2026-02-01'),
  (3, 2, 0.64, 0.64, 0, '2026-03-01'),
  (3, 2, 0.64, 0.64, 0, '2026-04-01'),
  (3, 3, 0.55, 0.55, 0, '2026-02-01'),
  (3, 3, 0.55, 0.55, 0, '2026-03-01'),
  (3, 3, 0.55, 0.55, 0, '2026-04-01'),
  (3, 4, 0.48, 0.48, 0, '2026-02-01'),
  (3, 4, 0.48, 0.48, 0, '2026-03-01'),
  (3, 4, 0.48, 0.48, 0, '2026-04-01'),
  (3, 5, 0.64, 0.64, 0, '2026-02-01'),
  (3, 5, 0.64, 0.64, 0, '2026-03-01'),
  (3, 5, 0.64, 0.64, 0, '2026-04-01'),
  (4, 1, 2.99, 2.99, 0, '2026-02-01'),
  (4, 1, 2.99, 2.99, 0, '2026-03-01'),
  (4, 1, 2.99, 2.99, 0, '2026-04-01'),
  (4, 2, 3.23, 3.23, 0, '2026-02-01'),
  (4, 2, 3.23, 3.23, 0, '2026-03-01'),
  (4, 2, 3.23, 3.23, 0, '2026-04-01'),
  (4, 3, 2.81, 2.81, 0, '2026-02-01'),
  (4, 3, 2.81, 2.81, 0, '2026-03-01'),
  (4, 3, 2.81, 2.81, 0, '2026-04-01'),
  (4, 4, 1.96, 2.45, 1, '2026-02-01'),
  (4, 4, 2.45, 2.45, 0, '2026-03-01'),
  (4, 4, 2.45, 2.45, 0, '2026-04-01'),
  (4, 5, 3.23, 3.23, 0, '2026-02-01'),
  (4, 5, 3.23, 3.23, 0, '2026-03-01'),
  (4, 5, 3.23, 3.23, 0, '2026-04-01'),
  (5, 1, 1.49, 1.49, 0, '2026-02-01'),
  (5, 1, 1.49, 1.49, 0, '2026-03-01'),
  (5, 1, 1.49, 1.49, 0, '2026-04-01'),
  (5, 2, 1.61, 1.61, 0, '2026-02-01'),
  (5, 2, 1.61, 1.61, 0, '2026-03-01'),
  (5, 2, 1.61, 1.61, 0, '2026-04-01'),
  (5, 3, 1.4, 1.4, 0, '2026-02-01'),
  (5, 3, 1.4, 1.4, 0, '2026-03-01'),
  (5, 3, 1.4, 1.4, 0, '2026-04-01'),
  (5, 4, 1.22, 1.22, 0, '2026-02-01'),
  (5, 4, 1.22, 1.22, 0, '2026-03-01'),
  (5, 4, 1.22, 1.22, 0, '2026-04-01'),
  (5, 5, 1.61, 1.61, 0, '2026-02-01'),
  (5, 5, 1.61, 1.61, 0, '2026-03-01'),
  (5, 5, 1.29, 1.61, 1, '2026-04-01');

-- ------------------------------------------------------------
-- shopping_lists (5 rows, spread across 3 users)
-- ------------------------------------------------------------
INSERT INTO shopping_lists (user_id, list_name, is_active) VALUES
  (1, 'Weekly Groceries', 1),
  (1, 'Costco Run',       1),
  (2, 'Meal Prep',        1),
  (3, 'Quick Trip',       1),
  (2, 'Old List',         0);

-- ------------------------------------------------------------
-- list_items (5 rows across the 5 lists above)
-- ------------------------------------------------------------
INSERT INTO list_items (list_id, product_id, quantity, checked) VALUES
  (1, 1, 2, 0),  -- Alice's Weekly list: 2x Whole Milk, not checked
  (1, 3, 1, 1),  -- Alice's Weekly list: 1x Bananas, already checked off
  (2, 2, 3, 0),  -- Alice's Costco run: 3x Chicken Breast
  (3, 5, 2, 0),  -- Bob's Meal Prep: 2x Pasta
  (4, 4, 1, 0);  -- Admin's Quick Trip: 1x Bread

-- ------------------------------------------------------------
-- posts (5 rows)
-- ------------------------------------------------------------
INSERT INTO posts (user_id, title, body, posted_at) VALUES
  (1, 'Publix BOGO this week!',
      'Publix has buy one get one free on chicken breast. Stock up!',
      '2026-04-20 10:00:00'),
  (2, 'Aldi vs Kroger egg prices',
      'Aldi is $1.40 cheaper per dozen than Kroger right now. Worth the drive.',
      '2026-04-18 14:30:00'),
  (3, 'Milk prices going up',
      'Noticed whole milk jumped 30 cents at Walmart this month.',
      '2026-04-15 09:15:00'),
  (1, 'Best store for produce?',
      'I have been comparing and Walmart has the freshest bananas lately.',
      '2026-04-10 17:00:00'),
  (4, 'Kroger digital coupons tip',
      'Load your Kroger digital coupons before shopping. Got $8 off this week!',
      '2026-04-05 08:45:00');

-- ============================================================
-- End of data.sql
-- Row counts:
--   users:          5
--   stores:         5
--   products:       5
--   price_records:  75  (5 products x 5 stores x 3 months)
--   shopping_lists: 5
--   list_items:     5
--   posts:          5
-- ============================================================